name: fossfit
description: Track gym progress, visualize graphs, enjoy offline support & timers
publish_to: none
version: 1.0.0
environment:
  sdk: ">=3.2.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2
  path: ^1.8.3
  csv: ^8.0.0
  intl: ^0.20.2
  fl_chart: ^1.0.0
  permission_handler: ^13.0.2
  provider: ^6.1.1
  dynamic_color: ^1.7.0
  sqlite3: ^3.5.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2
  file_picker: ^13.1.0
  share_plus: ^13.3.0
  audioplayers: ^6.5.0
  package_info_plus: ^10.2.1
  url_launcher: ^6.2.6
  badges: ^3.1.2
  flutter_local_notifications: ^22.3.1
  msvcredist:
    git:
      url: https://github.com/insertjokehere/flutter_msvcredist.git
      ref: main
  timeago: ^3.2.2
  sqlite3_web: ^0.9.4
  sticky_headers: ^0.3.0+2
  table_calendar: ^3.2.1
  flutter_local_notifications_platform_interface: ^12.2.0
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0
  platform_detail: ^5.5.0
  collection: ^1.19.1
  file_selector_android: ^0.5.2+4
  file_selector_linux: ^0.9.4
  file_selector_windows: ^0.9.3+5
  file_selector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  drift_dev: ^2.28.1
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.14.4
  msix:
    git:
      url: https://github.com/insertjokehere/msix.git
      ref: msvc_redist
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Wolland
      fonts:
        - asset: assets/fonts/Wolland.ttf
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
          weight: 100
          style: normal

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic

    - family: Lunasima
      fonts:
        - asset: assets/fonts/Lunasima/Lunasima-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lunasima/Lunasima-Regular.ttf
          weight: 400

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
          weight: 100
          style: normal

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-VariableFont_wdth,wght.ttf
          weight: 100
          style: normal

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-VariableFont_wdth,wght.ttf
          weight: 100
          style: normal

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf
          weight: 100
          style: normal

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/ic_launcher.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/ic_launcher.png
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: assets/ic_launcher.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/ic_launcher.png
  linux:
    generate: true
    image_path: assets/ic_launcher.png
msix_config:
  msstore_appId: 9P13THVK7F69
  display_name: FossFit
  publisher_display_name: ChrisKustom
  identity_name: KustomSoftware.FossFit
  msix_version: 1.0.175.0
  logo_path: assets/ic_launcher.png
  trim_logo: false
  publisher: CN=BB0811CB-EED5-441C-BE1B-D31F391F76DE
  store: true
